# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Theme selection
# Default theme -- contains ALL assets and configs -- use for testing
# theme: "_grusp_base"
# Actual conference theme -- only contains the specific assets (copy from _grusp_base as needed)
theme: "grusp_conf"

# Site / OG
type: website
slug: sfday
edition: 2021
title: "sfday 2020"
description: "sfday 2020, online conference"
#   separate keywords by comma, no spaces
keywords: conference,software conference,symfony,php,tech conference
author: GrUSP
language: en
timezone: 'Europe/Rome'
# si può sostituire con il logo della conferenza (`img/conference-logo.png`)
image: 'img/grusp-logo-full.png'
open_graph:
  # si può sostituire con il logo della conferenza (`img/conference-logo.png`)
  image: 'img/grusp-logo-full.png'
twitter:
  twitter_id: rubydayit
fb:
  fb_id: rubydayit

# Breadcrumbs
breadcrumb:
  display: true

# URL
## If your site is put in a subdirectory, set url as 'yoursite.com/child' and root as '/child/'
# TODO actual URL (per site)
url: https://2021.rubyday.it/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
date_format_extended: MMMM DD, YYYY
date_format_hero: MMMM DD, YYYY HH:mm
date_format_hero_online: MMMM DD, YYYY HH:mm z
time_format_schedule: HH:mm

# responsive images
responsive_images:
  - pattern: '**/*.+(jpg|jpeg)'
    sizes:
      mobile_small:
        width: 360
        height: 640
      mobile_medium:
        width: 600
        height: 1066
      tablet_vertical:
        width: 1024
        height: 1366
      tablet:
        width: 1024
        height: 576
      desktop:
        width: 1215
        height: 684
      widescreen:
        width: 1407
        height: 792
    fit: cover
    quality: 80
    withoutEnlargement: true

############# standard config: do not change

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: page
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: ''

node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false
  includePaths:
    - "./node_modules"
